In [6]:
import numpy as np





In [8]:
sample_ndarray = np.array([1, 2, 3])
print(sample_ndarray + 1)

[2 3 4]


In [13]:
sample_ndarray = np.array([[1, 2, 3], [4, 5, 6]])
print(sample_ndarray)

[[1 2 3]
 [4 5 6]]


In [14]:
print(np.array([2, 2, 2]) + np.array([1, 2, 3]))

[3 4 5]


In [17]:
print(np.array([[1, 2, 3], [1,2,45]]).shape) 

(2, 3)


In [19]:
sample_ndarray = np.arange(100)
print(sample_ndarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [21]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
sample_ndarray = np.arange(50, 200, 2)
print(sample_ndarray)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156
 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192
 194 196 198]


In [23]:
np.array(range(50, 200, 2))

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100,
       102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [24]:
sample_ndarray = np.ones(100)
print(sample_ndarray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [25]:
sample_ndarray = np.ones(10)
print(sample_ndarray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
sample_ndarray = np.full(100, 7)
print(sample_ndarray)


[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [30]:
sample_ndarray = np.arange(10)
print(sample_ndarray)
print(sample_ndarray[3]) # Extract the third element
print(sample_ndarray[:3]) # Extract up to the previous element of the third element as an array
print(sample_ndarray[-1]) # Extract the last element
print(sample_ndarray[::6]) # With 2 steps, take out an array that skips one
print(sample_ndarray[::-1]) # Extract the reverse array

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2]
9
[0 6]
[9 8 7 6 5 4 3 2 1 0]


In [31]:
a_ndarray = np.arange(4)
print(a_ndarray.shape) # (4,)
b_ndarray = a_ndarray.reshape(2, 2)
print(b_ndarray)
print(b_ndarray.shape) # (2, 2)

(4,)
[[0 1]
 [2 3]]
(2, 2)


In [37]:
sample_ndarray = np.arange(9).reshape(3, 3)
print(sample_ndarray)
#sample_ndarray[1, 2] # Extract the elements in the 1st row and 2nd column
sample_ndarray[:, 1:] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
a_ndarray = np.arange(6)
b_ndarray = a_ndarray.reshape(2, 3)
print(b_ndarray)
print(f"shape is {b_ndarray.shape}")#.format(b_ndarray.shape)) # (2, 3)
print("The total value is {}".format(b_ndarray.sum())) # 15
print("The total in the 0th axial direction is {}".format(b_ndarray.sum(axis=1))) # [3 5 7]
print("The average in the first axial direction is {}".format(b_ndarray.mean(axis=1))) # [1. 4.]

[[0 1 2]
 [3 4 5]]
shape is (2, 3)
The total value is 15
The total in the 0th axial direction is [ 3 12]
The average in the first axial direction is [1. 4.]
