In [24]:
import numpy as np
import matplotlib.pyplot as plt

**[Problem 1] Matrix product is calculated manually**

For matrix multiplication, we just need to take the scala multiplication of the row of the first matrix with the corresponding column of the second matrix, then sum them all together.

In [29]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], 
                      [0, 2, -8], 
                      [2, 9, -1]])

In [36]:
result = [[-1*0+2*0+3*2, -1*2+2*2+3*9, -1*1+2*-8+3*-1],
          [4*0+-5*0+6*2,4*2-5*2+6*9, 4*1+-5*-8+6*-1],
          [7*0+8*0+-9*2,7*2+8*2+-9*9,7*1+8*-8-9*-1]]
result

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]

**[Problem 2] Calculation by NumPy function**

In [27]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [37]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [38]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

**[Problem 3] Implementation of calculation of a certain element**

In [40]:
scala_mul = 0
for i in range(len(a_ndarray[0])):
    scala_mul += a_ndarray[0][i]*b_ndarray[i][0]
scala_mul

6

**[Problem 4] Creating a function that performs matrix multiplication**

In [32]:
def matrix_mul(a_ndarray, b_ndarray):  
  result = np.empty([len(a_ndarray), len(b_ndarray[0])])
  for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        for k in range(len(b_ndarray)):
            result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
  return result

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

**[Problem 5] Judge the input whose calculation is not defined**

In [41]:
def matrix_mul_judged(a_ndarray, b_ndarray):
  if (len(a_ndarray[0]) != len(b_ndarray)):
    print("Cannot multiply")
    return
  result = np.empty([len(a_ndarray), len(b_ndarray[0])])
  for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        for k in range(len(b_ndarray)):
            result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
  return result

In [ ]:
matrix_mul_judged(a_ndarray, [1,2,3])

In [42]:
matrix_mul_judged([[1,2],[3,4]], [1,2,3])

Cannot multiply


**[Problem 6] Transposition**

In [43]:
x_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9],
                      [2, 3, 4]])
y_ndarray = np.array([[0, 2, 1], 
                      [0, 2, -8], 
                      [2, 9, -1],
                      [2, 3, 4]])

In [44]:
np.matmul(x_ndarray, y_ndarray)

ValueError: ignored

In [45]:
np.matmul(np.transpose(x_ndarray), y_ndarray)

array([[ 18,  75, -32],
       [ 22,  75,  46],
       [-10, -51, -20]])