**<h1><center>Utilization of object orientation</center></h1>**

**[Problem 1] Enumeration of classes used so far**

*  In pandas, we have: GroupBy, Dataframe, Series, ...
*  In matplotlib, we have: Legend, Figure, SubFigure, ...
*  In sklearn, we have: StandardScaler, SVC, SVR,






**[Problem 2] Enumeration of methods and instance variables used so far**

Some methods used belonging to class:

*   pandas: head(), tail(), info(), describe(), drop(), isnull(), notnull(), ...
*   matplotlib: plot(), set_xlabel(), set_ylabel(), set_title(), show(), ...
*   sklearn: fit(), fit_transform(), transform(), predict(), accuracy_score(), ...





**[Problem 3] Creating a standardized class by scratch**

In [ ]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean : {}".format(scratch_scaler.mean_))
print("Var : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [ ]:
# Check with library
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
print("Mean : {}".format(scaler.mean_))
print("Var : {}".format(scaler.var_))
X_std = scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


**[Problem 4] Creating a class that performs 4 arithmetic operations**

In [ ]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        assert type(value) in [int, float], "Initial value must be numeric"
        self.value = value
        print(f"Initial value {self.value} has been set")
        
    def add(self, value2):
        self.value += value2
    
    def subtract(self, value2):
        self.value -= value2
    
    def multiply(self, value2):
        self.value *= value2
    
    def divide(self, value2):
        self.value /= value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(3)
print("value : {}".format(example.value))
example.multiply(3)
print("value : {}".format(example.value))
example.divide(2)
print("value : {}".format(example.value))

Initial value 5 has been set
value : 5
value : 8
value : 5
value : 15
value : 7.5


In [ ]:
# Test invalid input
error = ExampleClass('string')
print("value: {}".format(error.value))

AssertionError: ignored